# Generated by Django 2.2.5 on 2021-07-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='lovation',
            new_name='location',
        ),
    ]
